name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: swarmus/embedded
    steps:
    - uses: actions/checkout@v2

    - name: prepare
      run: |
        mkdir -p build
        cd build
        cmake -DENABLE_WARNINGS_AS_ERROR=ON -DENABLE_CLANG_TIDY_CHECK=ON -DCMAKE_BUILD_TYPE=Debug ..  
    - name: build
      run: |
        cd build
        make -j

    - name: tests
      run: |
        cd build
        ctest -v

    - name: check-format
      run: |
        cd build
        make check-format

    # Verifies that the doc is built
    - name: doc
      run: |
        cd build
        make doc