name: Publish Documentation

on:
  push:
    branches: [ master ]

jobs:
  build-native:
    runs-on: ubuntu-20.04
    container:
      image: swarmus/embedded
    steps:
      - uses: actions/checkout@v2

      - name: prepare
        run: |
          apt-get update && apt-get install -y rsync
          mkdir -p build
          cd build
          cmake ..

      - name: build
        run: |
          cd build
          make -j

      - name: generate
        run: |
          cd build
          make doc

      - name: publish
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build/doc/html
          TARGET_FOLDER: docs
          CLEAN: true
          SINGLE_COMMIT: true

